### PR TITLE
Backport useful changes from later 1.3.x and 1.4.x

### PR DESCRIPTION
**Pull request by ojwb**
The first 3 fixes are for issues reported by Will.

b0882bd disables building static libraries which I doubt you're using.  Currently most sources get compiled twice making builds needlessly take longer, and the unused static library then takes up disk space on the machines.  This probably will need a matching tweak to the debian packaging, which I can sort out.

67a5f2c and 182517d only affect builds with `--enable-assertions` but that's useful for development and debugging work.

c012be8 is only useful if we're going to backport the Arabic stemmer too (see email about that).

671e4e3 is only useful if CJK ngrams are enabled, which I don't see any use of.  However, it also only changes code on the CJK ngrams code path and in the test suite.

7ccf59c fixes incorrect results in a case which I'm not sure if you actually exercise, but the change simply initialises allocated memory to 0 which was previously not initialised, so it seems worth having.

### CODE REVIEW

**Comment by ojwb** [comment]
#9 has the debian packaging changes to go with  b0882bd.

I've pushed an extra commit to this PR's branch which merges in the Arabic stemmer.  I've tested this locally and in compiles and the tests pass (jenkins seems to skip all the "stemdict" tests for reasons I haven't managed to suss out).

**Review by ptomato — APPROVED** [review]
I'm good with this if it builds on Jenkins

@cosimoc @ebassi Did you want to take a look?

**Comment by cosimoc** [comment]
Yep, this makes sense and matches what we discussed yesterday. Thanks!

**Comment by cosimoc** [comment]
@wgreenberg FYI -- now that this is in, I filed https://phabricator.endlessm.com/T19372 for the SOMA side.
@ptomato Do you want to create a ticket to track this on the SDK board?

**Pull request merged**
